{
	"exceptions": {
		"auth": {
			"invalid_credentials": "Credenciales inv√°lidas"
		},
		"user": {
			"not_found": "Usuario no encontrado",
			"already_exists": "El usuario ya existe"
		},
		"unexpected_error": "Un error inesperado ha ocurrido"
	}
}